"""empty message

Revision ID: 108c1f341dea
Revises: 65a531b495aa
Create Date: 2022-07-15 15:11:32.164633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108c1f341dea'
down_revision = '65a531b495aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('annotation_id', sa.String(), nullable=False),
    sa.Column('annotation_name', sa.String(), nullable=False),
    sa.Column('website_id', sa.String(), nullable=False),
    sa.Column('website_uri', sa.String(), nullable=False),
    sa.Column('html_node_data_tag', sa.String(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('annotation_id', 'annotation_name'),
    sa.UniqueConstraint('annotation_id'),
    sa.UniqueConstraint('annotation_name'),
    sa.UniqueConstraint('html_node_data_tag'),
    sa.UniqueConstraint('website_id')
    )
    op.create_table('token',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('website',
    sa.Column('website_id', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('n_annotations', sa.Integer(), nullable=True),
    sa.Column('annotation_limit', sa.Integer(), nullable=True),
    sa.Column('admin', sa.String(), nullable=False),
    sa.Column('admin_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('website_id'),
    sa.UniqueConstraint('admin'),
    sa.UniqueConstraint('website_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website')
    op.drop_table('user')
    op.drop_table('token')
    op.drop_table('annotation')
    # ### end Alembic commands ###
