"""empty message

Revision ID: 1a9d9f6baa80
Revises: 
Create Date: 2022-07-10 23:53:56.177033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9d9f6baa80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email_id', sa.String(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('app_preferences', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('authority'),
    sa.UniqueConstraint('email_id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('webhook_url')
    )
    op.create_table('annotation',
    sa.Column('annotation_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('html_content', sa.String(), nullable=False),
    sa.Column('parent_node', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('mod_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('annotation_id'),
    sa.UniqueConstraint('annotation_id')
    )
    op.create_table('html_node_data',
    sa.Column('website_id', sa.String(), nullable=False),
    sa.Column('website_url', sa.String(), nullable=False),
    sa.Column('html_node', sa.String(), nullable=False),
    sa.Column('html_parent_node', sa.String(), nullable=True),
    sa.Column('html_node_class', sa.String(), nullable=True),
    sa.Column('html_node_id', sa.String(), nullable=True),
    sa.Column('annotation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.annotation_id'], ),
    sa.PrimaryKeyConstraint('website_id'),
    sa.UniqueConstraint('website_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('html_node_data')
    op.drop_table('annotation')
    op.drop_table('user')
    # ### end Alembic commands ###
