"""empty message

Revision ID: 1c74814b02d9
Revises: ab9228e5be39
Create Date: 2022-07-15 17:27:49.171907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c74814b02d9'
down_revision = 'ab9228e5be39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('tags', sa.String(), nullable=True))
    op.drop_column('comment', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.drop_column('annotation', 'tags')
    # ### end Alembic commands ###
