"""empty message

Revision ID: 3a57ad5ef3a7
Revises: 6c80350dc52c
Create Date: 2022-08-04 14:29:08.299157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a57ad5ef3a7'
down_revision = '6c80350dc52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upvotes', sa.String(), nullable=True))
    op.add_column('user', sa.Column('downvotes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'downvotes')
    op.drop_column('user', 'upvotes')
    # ### end Alembic commands ###
