"""empty message

Revision ID: 4f21a4924b69
Revises: 3a57ad5ef3a7
Create Date: 2022-08-09 12:09:11.035544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f21a4924b69'
down_revision = '3a57ad5ef3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('html_id', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('html_tag', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('html_text_content', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'annotation', ['html_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation', type_='unique')
    op.drop_column('annotation', 'html_text_content')
    op.drop_column('annotation', 'html_tag')
    op.drop_column('annotation', 'html_id')
    # ### end Alembic commands ###
