"""empty message

Revision ID: b71e3dde7c25
Revises: f60117ec6f80
Create Date: 2022-07-11 21:34:52.612519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71e3dde7c25'
down_revision = 'f60117ec6f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'annotation', ['website_id'])
    op.add_column('user', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('user', sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('user', 'app_preferences')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'webhook_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('webhook_url', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('app_preferences', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'bio')
    op.drop_constraint(None, 'annotation', type_='unique')
    # ### end Alembic commands ###
