"""empty message

Revision ID: b778f7e83bb0
Revises: cc846af476f9
Create Date: 2022-08-19 22:21:20.614469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b778f7e83bb0'
down_revision = 'cc846af476f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userpreference', 'show_resolved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpreference', sa.Column('show_resolved', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
