"""empty message

Revision ID: dc2c19ec11c9
Revises: 10a9fc7dc3cb
Create Date: 2022-07-14 20:46:20.650765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2c19ec11c9'
down_revision = '10a9fc7dc3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_column('user', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_key', sa.VARCHAR(), nullable=True))
    op.drop_table('token')
    # ### end Alembic commands ###
